### ISSUE TITLE
Nearest-neighbor Scaling?

### ISSUE THREAD

**Issue by OpenRift412** [RangerKoc/Neverhood-patch#2]
Great patch, works like a charm. My only complaint with it is that it only uses the blurry bilinear filter for scaling to the display's native resolution. Would this be something that could be added as like an option?

**Comment by RangerKoc** [comment]
Hello.
Please check new release version 1.2.

Added some options via creating files in game folder:
* integer-scale.mode - integer scaling in fullscreen mode;
* disable-scale-filter.mode - disable bilinear filter in fullscreen mode;
* scanlines.mode - enable CRT TV scanlines effect in fullscreen;
* windowed.mode - 1x scaled windowed mode;
* windowed2x.mode - 2x scaled windowed mode.

Have fun!

**Comment by OpenRift412** [comment]
> Hello. Please check new release version 1.2.
> 
> Added some options via creating files in game folder:
> 
> * integer-scale.mode - integer scaling in fullscreen mode;
> * disable-scale-filter.mode - disbale bilinear filter in fullscreen mode;
> * scanlines.mode - enable CRT TV scanlines effect in fullscreen;
> * windowed.mode - 1x scaled windowed mode;
> * windowed2x.mode - 2x scaled windowed mode.
> 
> Have fun!

Awesome man! Thanks a million!
