### ISSUE TITLE
Проблемы с рябью картинки/Pixels in the first person view

### ISSUE THREAD

**Issue by Alter73** [RangerKoc/Neverhood-patch#3]
Вы проделали огромную работу! Спасибо вам за то, что сейчас можно зайти и поностальгировать в игру детства. Если возможно, то можете помочь с одной небольшой проблемой? Дело в том, что в роликах (иногда и просто в действиях) картинка идёт рябью, экран прямо покрывается пикселями. Причём я отлично помню, что в оригинале такого не было, даже на YouTube зашёл посмотрел и такого, как у меня ни у кого нет. Если возможно, то посоветуйте как это можно исправить. Заранее спасибо.

**Comment by Alter73** [comment]
Ок, я нашёл причину, скачанный образ оказался битым (old-games.ru). Скачал новый и всё работает, извиняюсь за ложное сообщение.

**Comment by RangerKoc** [comment]
Прекрасно! А то я уже собирался запрашивать скриншоты :-)
