### ISSUE TITLE
Not An Issue, But A Thank You

### ISSUE THREAD

**Issue by Adore33** [RangerKoc/Neverhood-patch#4]
@RangerKoc

I'm sorry to put this here as I know it is not the right place.
I don't know if there is a way to message you on GitHub or not.

I just wanted to thank you for your patch for "The Neverhood".
It's people like you that keep these games alive and playable.
I and many others appreciate your hard work.

If you want to delete this post you can, or just ask me to.
Hope this message gets to you.

Thanks Friend.

**Comment by RangerKoc** [comment]
You welcome :-)
